# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigForm(object):
    def setupUi(self, ConfigForm):
        ConfigForm.setObjectName("ConfigForm")
        ConfigForm.resize(1188, 838)
        ConfigForm.setWindowTitle("Device Configuration")
        ConfigForm.setStyleSheet("QGroupBox { font-weight: bold; }")

        # Sampling Rate Configuration Group
        self.samplingRateGroup = QtWidgets.QGroupBox(ConfigForm)
        self.samplingRateGroup.setGeometry(QtCore.QRect(20, 20, 1160, 80))
        self.samplingRateGroup.setObjectName("samplingRateGroup")
        self.samplingRateGroup.setTitle("采样率配置")  # Sampling Rate Configuration

        self.samplingRateWidget = QtWidgets.QWidget(self.samplingRateGroup)
        self.samplingRateWidget.setGeometry(QtCore.QRect(10, 25, 1140, 45))
        self.samplingRateWidget.setObjectName("samplingRateWidget")
        
        self.samplingRateLayout = QtWidgets.QHBoxLayout(self.samplingRateWidget)
        self.samplingRateLayout.setContentsMargins(0, 0, 0, 0)
        self.samplingRateLayout.setObjectName("samplingRateLayout")

        # EEG Sampling Rate
        self.eegSamplingLabel = QtWidgets.QLabel(self.samplingRateWidget)
        self.eegSamplingLabel.setText("EEG (Hz):")
        self.eegSamplingLabel.setObjectName("eegSamplingLabel")
        self.samplingRateLayout.addWidget(self.eegSamplingLabel)

        self.eegSamplingCombo = QtWidgets.QComboBox(self.samplingRateWidget)
        self.eegSamplingCombo.setObjectName("eegSamplingCombo")
        self.eegSamplingCombo.addItems(["500", "1000", "2000"])
        self.eegSamplingCombo.setCurrentText("1000")
        self.samplingRateLayout.addWidget(self.eegSamplingCombo)

        # Add spacer
        horizontalSpacer1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.samplingRateLayout.addItem(horizontalSpacer1)

        # fNIRS Sampling Rate
        self.fnirsSamplingLabel = QtWidgets.QLabel(self.samplingRateWidget)
        self.fnirsSamplingLabel.setText("fNIRS (Hz):")
        self.fnirsSamplingLabel.setObjectName("fnirsSamplingLabel")
        self.samplingRateLayout.addWidget(self.fnirsSamplingLabel)

        self.fnirsSamplingCombo = QtWidgets.QComboBox(self.samplingRateWidget)
        self.fnirsSamplingCombo.setObjectName("fnirsSamplingCombo")
        self.fnirsSamplingCombo.addItems(["10", "20", "50"])
        self.fnirsSamplingCombo.setCurrentText("10")
        self.samplingRateLayout.addWidget(self.fnirsSamplingCombo)

        # Add spacer
        horizontalSpacer2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.samplingRateLayout.addItem(horizontalSpacer2)

        # sEMG Sampling Rate
        self.semgSamplingLabel = QtWidgets.QLabel(self.samplingRateWidget)
        self.semgSamplingLabel.setText("sEMG (Hz):")
        self.semgSamplingLabel.setObjectName("semgSamplingLabel")
        self.samplingRateLayout.addWidget(self.semgSamplingLabel)

        self.semgSamplingCombo = QtWidgets.QComboBox(self.samplingRateWidget)
        self.semgSamplingCombo.setObjectName("semgSamplingCombo")
        self.semgSamplingCombo.addItems(["500", "1000", "2000"])
        self.semgSamplingCombo.setCurrentText("1000")
        self.samplingRateLayout.addWidget(self.semgSamplingCombo)

        # Add spacer
        horizontalSpacer3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.samplingRateLayout.addItem(horizontalSpacer3)

        # Apply Settings Button
        # self.applySamplingBtn = QtWidgets.QPushButton(self.samplingRateWidget)
        # self.applySamplingBtn.setText("采样率设置")  # Apply Sampling Rate Settings
        # self.applySamplingBtn.setObjectName("applySamplingBtn")
        # self.samplingRateLayout.addWidget(self.applySamplingBtn)

        # Channel Configuration Group
        self.channelConfigGroup = QtWidgets.QGroupBox(ConfigForm)
        self.channelConfigGroup.setGeometry(QtCore.QRect(20, 110, 1160, 711))
        self.channelConfigGroup.setObjectName("channelConfigGroup")
        self.channelConfigGroup.setTitle("通道配置")  # Channel Configuration

        # Control Buttons Widget
        self.controlButtonsWidget = QtWidgets.QWidget(self.channelConfigGroup)
        self.controlButtonsWidget.setGeometry(QtCore.QRect(10, 25, 1140, 40))
        self.controlButtonsWidget.setObjectName("controlButtonsWidget")
        
        self.controlButtonsLayout = QtWidgets.QHBoxLayout(self.controlButtonsWidget)
        self.controlButtonsLayout.setContentsMargins(0, 0, 0, 0)
        self.controlButtonsLayout.setObjectName("controlButtonsLayout")

        self.loadConfigBtn = QtWidgets.QPushButton(self.controlButtonsWidget)
        self.loadConfigBtn.setText("加载配置")
        self.loadConfigBtn.setObjectName("loadConfigBtn")
        self.controlButtonsLayout.addWidget(self.loadConfigBtn)

        self.createConfigBtn = QtWidgets.QPushButton(self.controlButtonsWidget)
        self.createConfigBtn.setText("新建配置")
        self.createConfigBtn.setObjectName("createConfigBtn")
        self.controlButtonsLayout.addWidget(self.createConfigBtn)
        
        self.saveConfigBtn = QtWidgets.QPushButton(self.controlButtonsWidget)
        self.saveConfigBtn.setText("保存配置")
        self.saveConfigBtn.setObjectName("saveConfigBtn")
        self.controlButtonsLayout.addWidget(self.saveConfigBtn)
        
        self.resetConfigBtn = QtWidgets.QPushButton(self.controlButtonsWidget)
        self.resetConfigBtn.setText("全部重置")
        self.resetConfigBtn.setObjectName("resetConfigBtn")
        self.controlButtonsLayout.addWidget(self.resetConfigBtn)

        # Control spacer
        controlSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlButtonsLayout.addItem(controlSpacer)

        self.generateConfigBtn = QtWidgets.QPushButton(self.controlButtonsWidget)
        self.generateConfigBtn.setText("设置")  # Channel Configuration Settings
        self.generateConfigBtn.setStyleSheet("QPushButton { background-color: #4CAF50; color: white; font-weight: bold; }")
        self.generateConfigBtn.setObjectName("generateConfigBtn")
        self.controlButtonsLayout.addWidget(self.generateConfigBtn)

        # Device Parameters Widget
        self.deviceParamsWidget = QtWidgets.QWidget(self.channelConfigGroup)
        self.deviceParamsWidget.setGeometry(QtCore.QRect(10, 75, 1140, 31))
        self.deviceParamsWidget.setObjectName("deviceParamsWidget")
        
        self.deviceParamsLayout = QtWidgets.QHBoxLayout(self.deviceParamsWidget)
        self.deviceParamsLayout.setContentsMargins(0, 0, 0, 0)
        self.deviceParamsLayout.setObjectName("deviceParamsLayout")

        # EEG Channels Layout
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.eegChannelsLabel_2 = QtWidgets.QLabel(self.deviceParamsWidget)
        self.eegChannelsLabel_2.setStyleSheet("font-weight: bold; color: #2196F3;")
        self.eegChannelsLabel_2.setText("EEG通道数:")  # EEG Channel Count
        self.eegChannelsLabel_2.setObjectName("eegChannelsLabel_2")
        self.horizontalLayout.addWidget(self.eegChannelsLabel_2)

        self.eegChannelsSpinBox_2 = QtWidgets.QSpinBox(self.deviceParamsWidget)
        self.eegChannelsSpinBox_2.setMinimum(1)
        self.eegChannelsSpinBox_2.setMaximum(256)
        self.eegChannelsSpinBox_2.setValue(32)
        self.eegChannelsSpinBox_2.setObjectName("eegChannelsSpinBox_2")
        self.horizontalLayout.addWidget(self.eegChannelsSpinBox_2)

        self.deviceParamsLayout.addLayout(self.horizontalLayout)

        # sEMG Channels Layout
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.semgChannelsLabel_2 = QtWidgets.QLabel(self.deviceParamsWidget)
        self.semgChannelsLabel_2.setStyleSheet("font-weight: bold; color: #FF9800;")
        self.semgChannelsLabel_2.setText("sEMG通道数:")  # sEMG Channel Count
        self.semgChannelsLabel_2.setObjectName("semgChannelsLabel_2")
        self.horizontalLayout_4.addWidget(self.semgChannelsLabel_2)

        self.semgChannelsSpinBox_2 = QtWidgets.QSpinBox(self.deviceParamsWidget)
        self.semgChannelsSpinBox_2.setMinimum(1)
        self.semgChannelsSpinBox_2.setMaximum(64)
        self.semgChannelsSpinBox_2.setValue(8)
        self.semgChannelsSpinBox_2.setObjectName("semgChannelsSpinBox_2")
        self.horizontalLayout_4.addWidget(self.semgChannelsSpinBox_2)

        self.deviceParamsLayout.addLayout(self.horizontalLayout_4)

        # fNIRS Sources Layout
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.fnirsSourcesLabel_2 = QtWidgets.QLabel(self.deviceParamsWidget)
        self.fnirsSourcesLabel_2.setStyleSheet("font-weight: bold; color: #E91E63;")
        self.fnirsSourcesLabel_2.setText("fNIRS光源数:")  # fNIRS Light Source Count
        self.fnirsSourcesLabel_2.setObjectName("fnirsSourcesLabel_2")
        self.horizontalLayout_2.addWidget(self.fnirsSourcesLabel_2)

        self.fnirsSourcesSpinBox_2 = QtWidgets.QSpinBox(self.deviceParamsWidget)
        self.fnirsSourcesSpinBox_2.setMinimum(1)
        self.fnirsSourcesSpinBox_2.setMaximum(32)
        self.fnirsSourcesSpinBox_2.setValue(8)
        self.fnirsSourcesSpinBox_2.setObjectName("fnirsSourcesSpinBox_2")
        self.horizontalLayout_2.addWidget(self.fnirsSourcesSpinBox_2)

        self.deviceParamsLayout.addLayout(self.horizontalLayout_2)

        # fNIRS Detectors Layout
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.fnirsDetectorsLabel_2 = QtWidgets.QLabel(self.deviceParamsWidget)
        self.fnirsDetectorsLabel_2.setStyleSheet("font-weight: bold; color: #1040ff")
        self.fnirsDetectorsLabel_2.setText("fNIRS探测器数:")  # fNIRS Detector Count
        self.fnirsDetectorsLabel_2.setObjectName("fnirsDetectorsLabel_2")
        self.horizontalLayout_3.addWidget(self.fnirsDetectorsLabel_2)

        self.fnirsDetectorsSpinBox_2 = QtWidgets.QSpinBox(self.deviceParamsWidget)
        self.fnirsDetectorsSpinBox_2.setMinimum(1)
        self.fnirsDetectorsSpinBox_2.setMaximum(32)
        self.fnirsDetectorsSpinBox_2.setValue(8)
        self.fnirsDetectorsSpinBox_2.setObjectName("fnirsDetectorsSpinBox_2")
        self.horizontalLayout_3.addWidget(self.fnirsDetectorsSpinBox_2)
        self.deviceParamsLayout.addLayout(self.horizontalLayout_3)
        
        # Add horizontal spacer
        horizontalSpacer_4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deviceParamsLayout.addItem(horizontalSpacer_4)
        
        # # Apply Settings Button
        # self.applyChannelBtn = QtWidgets.QPushButton(self.deviceParamsWidget)
        # self.applyChannelBtn.setText("通道数设置")  # Apply Sampling Rate Settings
        # self.applyChannelBtn.setObjectName("applyChannelBtn")
        # self.deviceParamsLayout.addWidget(self.applyChannelBtn)
        
        # Configuration Tab Widget
        self.configTabWidget = QtWidgets.QTabWidget(self.channelConfigGroup)
        self.configTabWidget.setGeometry(QtCore.QRect(10, 110, 1140, 595))
        self.configTabWidget.setCurrentIndex(0)
        self.configTabWidget.setObjectName("configTabWidget")

        # Brain (EEG) Configuration Tab
        self.barinTab = QtWidgets.QWidget()
        self.barinTab.setObjectName("barinTab")
        self.configTabWidget.addTab(self.barinTab, "Brain Configuration")

        self.BrainScrollArea = QtWidgets.QScrollArea(self.barinTab)
        self.BrainScrollArea.setGeometry(QtCore.QRect(5, 5, 560, 560))
        self.BrainScrollArea.setWidgetResizable(True)
        self.BrainScrollArea.setObjectName("BrainScrollArea")

        self.BrainScrollWidget = QtWidgets.QWidget()
        self.BrainScrollWidget.setGeometry(QtCore.QRect(0, 0, 558, 558))
        self.BrainScrollWidget.setObjectName("BrainScrollWidget")
        self.BrainScrollArea.setWidget(self.BrainScrollWidget)

        self.eegGridLayout = QtWidgets.QGridLayout(self.BrainScrollWidget)
        self.eegGridLayout.setObjectName("eegGridLayout")

        # Add second widget for brain tab (placeholder)
        self.widget_2 = QtWidgets.QWidget(self.barinTab)
        self.widget_2.setGeometry(QtCore.QRect(570, 5, 560, 560))
        self.widget_2.setObjectName("widget_2")
        
        # Trunk (sEMG) Configuration Tab
        self.trunkTab = QtWidgets.QWidget()
        self.trunkTab.setObjectName("trunkTab")
        self.configTabWidget.addTab(self.trunkTab, "Trunk Configuration")

        self.trunkScrollArea = QtWidgets.QScrollArea(self.trunkTab)
        self.trunkScrollArea.setGeometry(QtCore.QRect(5, 5, 560, 560))
        self.trunkScrollArea.setWidgetResizable(True)
        self.trunkScrollArea.setObjectName("trunkScrollArea")

        self.trunkScrollWidget = QtWidgets.QWidget()
        self.trunkScrollWidget.setGeometry(QtCore.QRect(0, 0, 558, 558))
        self.trunkScrollWidget.setObjectName("trunkScrollWidget")
        self.trunkScrollArea.setWidget(self.trunkScrollWidget)

        self.semgGridLayout = QtWidgets.QGridLayout(self.trunkScrollWidget)
        self.semgGridLayout.setObjectName("semgGridLayout")

        # Add second widget for trunk tab (placeholder)
        self.widget_3 = QtWidgets.QWidget(self.trunkTab)
        self.widget_3.setGeometry(QtCore.QRect(570, 5, 560, 560))
        self.widget_3.setObjectName("widget_3")

        # Empty third tab
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.configTabWidget.addTab(self.widget, "")

        QtCore.QMetaObject.connectSlotsByName(ConfigForm)

    def retranslateUi(self, ConfigForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigForm.setWindowTitle(_translate("ConfigForm", "Device Configuration"))
        self.samplingRateGroup.setTitle(_translate("ConfigForm", "采样率配置"))
        self.eegSamplingLabel.setText(_translate("ConfigForm", "EEG (Hz):"))
        self.fnirsSamplingLabel.setText(_translate("ConfigForm", "fNIRS (Hz):"))
        self.semgSamplingLabel.setText(_translate("ConfigForm", "sEMG (Hz):"))
        self.applySamplingBtn.setText(_translate("ConfigForm", "采样率设置"))
        self.channelConfigGroup.setTitle(_translate("ConfigForm", "通道配置"))
        self.loadConfigBtn.setText(_translate("ConfigForm", "Load Configuration"))
        self.createConfigBtn.setText(_translate("ConfigForm", "Save Configuration"))
        self.resetConfigBtn.setText(_translate("ConfigForm", "Reset All"))
        self.generateConfigBtn.setText(_translate("ConfigForm", "通道配置设置"))
        self.eegChannelsLabel_2.setText(_translate("ConfigForm", "EEG通道数:"))
        self.semgChannelsLabel_2.setText(_translate("ConfigForm", "sEMG通道数:"))
        self.fnirsSourcesLabel_2.setText(_translate("ConfigForm", "fNIRS光源数:"))
        self.fnirsDetectorsLabel_2.setText(_translate("ConfigForm", "fNIRS探测器数:"))
        self.configTabWidget.setTabText(self.configTabWidget.indexOf(self.barinTab), _translate("ConfigForm", "Brain Configuration"))
        self.configTabWidget.setTabText(self.configTabWidget.indexOf(self.trunkTab), _translate("ConfigForm", "Trunk Configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfigForm = QtWidgets.QWidget()
    ui = Ui_ConfigForm()
    ui.setupUi(ConfigForm)
    ConfigForm.show()
    sys.exit(app.exec_())