# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DisplayWidget(object):
    """UI class for the Display Widget - handles only UI setup and styling"""
    
    def setupUi(self, DisplayWidget):
        DisplayWidget.setObjectName("DisplayWidget")
        DisplayWidget.resize(1200, 850)
        DisplayWidget.setMinimumSize(QtCore.QSize(1000, 700))
        
        # Apply default styling
        self.apply_default_style(DisplayWidget)
        
        # Main layout
        self.mainLayout = QtWidgets.QVBoxLayout(DisplayWidget)
        self.mainLayout.setContentsMargins(5, 5, 5, 5)
        self.mainLayout.setSpacing(2)
        self.mainLayout.setObjectName("mainLayout")
        
        # Setup UI components
        self.setup_control_panel(DisplayWidget)
        self.setup_settings_panel(DisplayWidget)
        self.setup_plot_panel(DisplayWidget)
        
        # Apply text translations
        self.retranslateUi(DisplayWidget)
        
        # Setup additional UI properties
        self.setup_additional_properties()
        
        # Connect slots by name
        QtCore.QMetaObject.connectSlotsByName(DisplayWidget)

    def setup_control_panel(self, parent):
        """Setup the control panel group box"""
        self.controlGroup = QtWidgets.QGroupBox(parent)
        self.controlGroup.setMaximumHeight(60)
        self.controlGroup.setObjectName("controlGroup")
        
        self.controlLayout = QtWidgets.QHBoxLayout(self.controlGroup)
        self.controlLayout.setObjectName("controlLayout")
        
        # Create control buttons            
        self.startButton = QtWidgets.QPushButton(self.controlGroup)
        self.startButton.setMinimumSize(QtCore.QSize(80, 30))
        self.startButton.setObjectName("startButton")
        self.startButton.setText("开始")
        self.controlLayout.addWidget(self.startButton)
        
        self.resetButton = QtWidgets.QPushButton(self.controlGroup)
        self.resetButton.setMinimumSize(QtCore.QSize(80, 30))
        self.resetButton.setObjectName("resetButton")
        self.resetButton.setText("复位")
        self.controlLayout.addWidget(self.resetButton)
        
        self.recordButton = QtWidgets.QPushButton(self.controlGroup)
        self.recordButton.setMinimumSize(QtCore.QSize(80, 30))
        self.recordButton.setObjectName("recordButton")
        self.recordButton.setText("记录")
        self.controlLayout.addWidget(self.recordButton)
        
        self.stopButton = QtWidgets.QPushButton(self.controlGroup)
        self.stopButton.setMinimumSize(QtCore.QSize(80, 30))
        self.stopButton.setObjectName("stopButton")
        self.stopButton.setText("停止")
        self.controlLayout.addWidget(self.stopButton)
        
        self.saveButton = QtWidgets.QPushButton(self.controlGroup)
        self.saveButton.setMinimumSize(QtCore.QSize(80, 30))
        self.saveButton.setObjectName("saveButton")
        self.saveButton.setText("保存")
        self.controlLayout.addWidget(self.saveButton)
        
        # Add spacer
        spacerItem = QtWidgets.QSpacerItem(40, 20, 
                                         QtWidgets.QSizePolicy.Expanding, 
                                         QtWidgets.QSizePolicy.Minimum)
        self.controlLayout.addItem(spacerItem)
        
        self.mainLayout.addWidget(self.controlGroup)

    def setup_settings_panel(self, parent):
        """Setup the settings panel group box"""
        self.settingsGroup = QtWidgets.QGroupBox(parent)
        self.settingsGroup.setMaximumHeight(60)
        self.settingsGroup.setObjectName("settingsGroup")
        
        self.settingsLayout = QtWidgets.QHBoxLayout(self.settingsGroup)
        self.settingsLayout.setObjectName("settingsLayout")
        
        # Signal type selection
        self.setup_signal_selection()
        
        # Filter type selection  
        self.setup_filter_selection()
        
        # Filter settings groups
        self.setup_sg_filter_group()
        self.setup_butterworth_filter_group()
        
        self.mainLayout.addWidget(self.settingsGroup)

    def setup_signal_selection(self):
        """Setup signal type selection controls"""
        self.signalLayout = QtWidgets.QHBoxLayout()
        self.signalLayout.setObjectName("signalLayout")
        
        self.signalTypeLabel = QtWidgets.QLabel(self.settingsGroup)
        self.signalTypeLabel.setObjectName("signalTypeLabel")
        self.signalLayout.addWidget(self.signalTypeLabel)
        
        self.signalTypeCombo = QtWidgets.QComboBox(self.settingsGroup)
        self.signalTypeCombo.setMinimumSize(QtCore.QSize(150, 25))
        self.signalTypeCombo.setObjectName("signalTypeCombo")
        
        # Add signal type items
        signal_types = [
            "原始光强",
            "光密度OD", 
            "血红蛋白浓度"
        ]
        
        for signal_type in signal_types:
            self.signalTypeCombo.addItem(signal_type)
        
        self.signalLayout.addWidget(self.signalTypeCombo)
        self.settingsLayout.addLayout(self.signalLayout)

    def setup_filter_selection(self):
        """Setup filter type selection controls"""
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        
        self.filterLabel = QtWidgets.QLabel(self.settingsGroup)
        self.filterLabel.setObjectName("filterLabel")
        self.filterLayout.addWidget(self.filterLabel)
        
        self.filterTypeCombo = QtWidgets.QComboBox(self.settingsGroup)
        self.filterTypeCombo.setMinimumSize(QtCore.QSize(120, 25))
        self.filterTypeCombo.setObjectName("filterTypeCombo")
        
        # Add filter type items
        filter_types = [
            "不滤波",
            "S-G滤波",
            "Butterworth滤波",
            "平滑滤波"
        ]
        
        for filter_type in filter_types:
            self.filterTypeCombo.addItem(filter_type)
        
        self.filterLayout.addWidget(self.filterTypeCombo)
        self.settingsLayout.addLayout(self.filterLayout)

    def setup_sg_filter_group(self):
        """Setup Savitzky-Golay filter settings group"""
        self.sgFilterGroup = QtWidgets.QGroupBox(self.settingsGroup)
        self.sgFilterGroup.setMinimumSize(QtCore.QSize(250, 60))
        self.sgFilterGroup.setVisible(False)  # Initially hidden
        self.sgFilterGroup.setObjectName("sgFilterGroup")
        
        self.sgLayout = QtWidgets.QHBoxLayout(self.sgFilterGroup)
        self.sgLayout.setObjectName("sgLayout")
        
        # Window size control
        self.windowLabel = QtWidgets.QLabel(self.sgFilterGroup)
        self.windowLabel.setObjectName("windowLabel")
        self.sgLayout.addWidget(self.windowLabel)
        
        self.windowSpinBox = QtWidgets.QSpinBox(self.sgFilterGroup)
        self.windowSpinBox.setMinimum(3)
        self.windowSpinBox.setMaximum(101)
        self.windowSpinBox.setSingleStep(2)
        self.windowSpinBox.setValue(11)
        self.windowSpinBox.setObjectName("windowSpinBox")
        self.sgLayout.addWidget(self.windowSpinBox)
        
        # Polynomial order control
        self.polyOrderLabel = QtWidgets.QLabel(self.sgFilterGroup)
        self.polyOrderLabel.setObjectName("polyOrderLabel")
        self.sgLayout.addWidget(self.polyOrderLabel)
        
        self.polyOrderSpinBox = QtWidgets.QSpinBox(self.sgFilterGroup)
        self.polyOrderSpinBox.setMinimum(1)
        self.polyOrderSpinBox.setMaximum(5)
        self.polyOrderSpinBox.setValue(3)
        self.polyOrderSpinBox.setObjectName("polyOrderSpinBox")
        self.sgLayout.addWidget(self.polyOrderSpinBox)
        
        # Apply button
        self.sgApplyButton = QtWidgets.QPushButton(self.sgFilterGroup)
        self.sgApplyButton.setMaximumSize(QtCore.QSize(80, 30))
        self.sgApplyButton.setObjectName("sgApplyButton")
        self.sgLayout.addWidget(self.sgApplyButton)
        
        self.settingsLayout.addWidget(self.sgFilterGroup)

    def setup_butterworth_filter_group(self):
        """Setup Butterworth filter settings group"""
        self.butterworthGroup = QtWidgets.QGroupBox(self.settingsGroup)
        self.butterworthGroup.setMinimumSize(QtCore.QSize(400, 80))
        self.butterworthGroup.setVisible(False)  # Initially hidden
        self.butterworthGroup.setObjectName("butterworthGroup")
        
        self.butterworthLayout = QtWidgets.QHBoxLayout(self.butterworthGroup)
        self.butterworthLayout.setObjectName("butterworthLayout")
        
        # Low cutoff frequency
        self.lowCutoffLabel = QtWidgets.QLabel(self.butterworthGroup)
        self.lowCutoffLabel.setObjectName("lowCutoffLabel")
        self.butterworthLayout.addWidget(self.lowCutoffLabel)
        
        self.lowCutoffEdit = QtWidgets.QLineEdit(self.butterworthGroup)
        self.lowCutoffEdit.setMaximumSize(QtCore.QSize(50, 25))
        self.lowCutoffEdit.setText("0.01")
        self.lowCutoffEdit.setObjectName("lowCutoffEdit")
        self.butterworthLayout.addWidget(self.lowCutoffEdit)
        
        # High cutoff frequency
        self.highCutoffLabel = QtWidgets.QLabel(self.butterworthGroup)
        self.highCutoffLabel.setObjectName("highCutoffLabel")
        self.butterworthLayout.addWidget(self.highCutoffLabel)
        
        self.highCutoffEdit = QtWidgets.QLineEdit(self.butterworthGroup)
        self.highCutoffEdit.setMaximumSize(QtCore.QSize(50, 25))
        self.highCutoffEdit.setText("0.1")
        self.highCutoffEdit.setObjectName("highCutoffEdit")
        self.butterworthLayout.addWidget(self.highCutoffEdit)
        
        # Filter order
        self.orderLabel = QtWidgets.QLabel(self.butterworthGroup)
        self.orderLabel.setObjectName("orderLabel")
        self.butterworthLayout.addWidget(self.orderLabel)
        
        self.orderSpinBox = QtWidgets.QSpinBox(self.butterworthGroup)
        self.orderSpinBox.setMinimum(1)
        self.orderSpinBox.setMaximum(10)
        self.orderSpinBox.setValue(4)
        self.orderSpinBox.setObjectName("orderSpinBox")
        self.butterworthLayout.addWidget(self.orderSpinBox)
        
        # Apply button
        self.butterworthApplyButton = QtWidgets.QPushButton(self.butterworthGroup)
        self.butterworthApplyButton.setMaximumSize(QtCore.QSize(80, 30))
        self.butterworthApplyButton.setObjectName("butterworthApplyButton")
        self.butterworthLayout.addWidget(self.butterworthApplyButton)
        
        self.settingsLayout.addWidget(self.butterworthGroup)

    def setup_plot_panel(self, parent):
        """Setup the plot panel group box"""
        self.plotGroup = QtWidgets.QGroupBox(parent)
        self.plotGroup.setObjectName("plotGroup")
        
        self.plotLayout = QtWidgets.QVBoxLayout(self.plotGroup)
        self.plotLayout.setSpacing(5)
        self.plotLayout.setObjectName("plotLayout")

        
        # Plot widget placeholder
        self.plotWidget = QtWidgets.QWidget(self.plotGroup)
        self.plotWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.plotWidget.setObjectName("plotWidget")
        self.plotLayout.addWidget(self.plotWidget)
        
        self.mainLayout.addWidget(self.plotGroup)

    def retranslateUi(self, DisplayWidget):
        """Setup text translations and labels"""
        _translate = QtCore.QCoreApplication.translate
        DisplayWidget.setWindowTitle(_translate("DisplayWidget", "Signal Processing and Data Visualization"))
        
        # Control panel
        self.controlGroup.setTitle(_translate("DisplayWidget", "Control Panel"))
        self.startButton.setText(_translate("DisplayWidget", "开始"))
        self.resetButton.setText(_translate("DisplayWidget", "复位"))
        self.recordButton.setText(_translate("DisplayWidget", "记录"))
        self.stopButton.setText(_translate("DisplayWidget", "停止"))
        self.saveButton.setText(_translate("DisplayWidget", "保存"))
        
        # Settings panel
        self.settingsGroup.setTitle(_translate("DisplayWidget", "Signal Processing Settings"))
        self.signalTypeLabel.setText(_translate("DisplayWidget", "信号类型:"))
        self.filterLabel.setText(_translate("DisplayWidget", "滤波:"))
        
        # S-G Filter settings
        self.sgFilterGroup.setTitle(_translate("DisplayWidget", "S-G Filter Settings"))
        self.windowLabel.setText(_translate("DisplayWidget", "窗口值:"))
        self.polyOrderLabel.setText(_translate("DisplayWidget", "多项式阶数:"))
        self.sgApplyButton.setText(_translate("DisplayWidget", "完成"))
        
        # Butterworth filter settings
        self.butterworthGroup.setTitle(_translate("DisplayWidget", "Butterworth Filter Settings"))
        self.lowCutoffLabel.setText(_translate("DisplayWidget", "下截止频率:"))
        self.highCutoffLabel.setText(_translate("DisplayWidget", "上截止频率:"))
        self.orderLabel.setText(_translate("DisplayWidget", "阶数:"))
        self.butterworthApplyButton.setText(_translate("DisplayWidget", "完成"))
        
        # Plot panel
        self.plotGroup.setTitle(_translate("DisplayWidget", "Data Visualization"))

    def setup_additional_properties(self):
        """Setup additional properties, tooltips, and initial states"""
        # Set tooltips for better user experience
        self.startButton.setToolTip("Start data acquisition")
        self.stopButton.setToolTip("Stop data acquisition")
        self.resetButton.setToolTip("Reset system and clear all data")
        self.recordButton.setToolTip("Toggle data recording")
        self.saveButton.setToolTip("Save recorded data to file")
        
        self.signalTypeCombo.setToolTip("Select signal type for processing")
        self.filterTypeCombo.setToolTip("Choose filter method")
        
        self.windowSpinBox.setToolTip("Window size for Savitzky-Golay filter (must be odd)")
        self.lowCutoffEdit.setToolTip("Lower cutoff frequency in Hz")
        self.highCutoffEdit.setToolTip("Upper cutoff frequency in Hz")
        self.orderSpinBox.setToolTip("Filter order (higher = steeper cutoff)")
        
        
        # Set focus policy for better keyboard navigation
        self.startButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.stopButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        
        # Enable/disable initial states
        self.stopButton.setEnabled(False)
        
        # Initially hide filter groups
        self.sgFilterGroup.setVisible(False)
        self.butterworthGroup.setVisible(False)

    def apply_default_style(self, widget):
        """Apply default styling to the widget"""
        style = """
            QWidget {
                background-color: #f5f5f5;
                font-family: "Segoe UI", Arial, sans-serif;
            }
            QGroupBox {
                font-weight: bold;
                font-size: 11px;
                border: 2px solid #cccccc;
                border-radius: 5px;
                margin-top: 10px;
                padding-top: 10px;
                background-color: #ffffff;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 5px 0 5px;
                color: #333333;
            }
            QPushButton {
                background-color: #4CAF50;
                border: none;
                color: white;
                padding: 8px 16px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 12px;
                border-radius: 4px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
            QPushButton:pressed {
                background-color: #3d8b40;
            }
            QPushButton:disabled {
                background-color: #cccccc;
                color: #666666;
            }
            QComboBox, QLineEdit, QSpinBox, QDoubleSpinBox {
                padding: 4px;
                border: 1px solid #ccc;
                border-radius: 3px;
                font-size: 11px;
                background-color: #ffffff;
            }
            QComboBox:focus, QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus {
                border: 2px solid #4CAF50;
            }
            QLabel {
                font-size: 11px;
                color: #333;
                background-color: transparent;
            }
        """
        widget.setStyleSheet(style)

    def setup_keyboard_shortcuts(self, widget):
        """Setup keyboard shortcuts for the widget"""
        # Note: This would typically be called from the main application
        # Since this is a widget, shortcuts should be handled by the parent application
        pass

    def get_filter_visibility_settings(self):
        """Return current filter group visibility settings"""
        return {
            'sg_visible': self.sgFilterGroup.isVisible(),
            'butterworth_visible': self.butterworthGroup.isVisible()
        }

    def set_filter_group_visibility(self, sg_visible=False, butterworth_visible=False):
        """Set visibility of filter groups"""
        self.sgFilterGroup.setVisible(sg_visible)
        self.butterworthGroup.setVisible(butterworth_visible)
        # Force layout update
        self.settingsGroup.update()

    def get_control_states(self):
        """Get current state of control buttons"""
        return {
            'start_enabled': self.startButton.isEnabled(),
            'stop_enabled': self.stopButton.isEnabled(),
            'reset_enabled': self.resetButton.isEnabled(),
            'record_enabled': self.recordButton.isEnabled(),
            'save_enabled': self.saveButton.isEnabled()
        }

    def set_control_states(self, **states):
        """Set control button states"""
        if 'start_enabled' in states:
            self.startButton.setEnabled(states['start_enabled'])
        if 'stop_enabled' in states:
            self.stopButton.setEnabled(states['stop_enabled'])
        if 'reset_enabled' in states:
            self.resetButton.setEnabled(states['reset_enabled'])
        if 'record_enabled' in states:
            self.recordButton.setEnabled(states['record_enabled'])
        if 'save_enabled' in states:
            self.saveButton.setEnabled(states['save_enabled'])


# Test the UI class independently
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    
    # Create a main window to hold the widget
    main_window = QtWidgets.QMainWindow()
    main_window.setWindowTitle("UI Display Test")
    
    # Create the display widget
    display_widget = QtWidgets.QWidget()
    ui = Ui_DisplayWidget()
    ui.setupUi(display_widget)
    
    # Set the widget as central widget
    main_window.setCentralWidget(display_widget)
    
    main_window.show()
    sys.exit(app.exec_())