# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
# Updated to match the exact UI structure defined in the XML file
# Optimized for responsive design and better code structure
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QSizePolicy

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 852)
        MainWindow.setMinimumSize(QtCore.QSize(900, 650))
        MainWindow.setWindowTitle("fNIRS Data Acquisition System")
        
        # Apply the exact stylesheet from the UI file
        self._apply_stylesheet(MainWindow)
        
        # Set up central widget with proper sizing
        self._setup_central_widget(MainWindow)
        
        # Create main tab widget
        self._setup_tab_widget()
        
        # Create all tabs
        self._create_all_tabs()
        
        # Create status area
        self._setup_status_area()
        
        # Set central widget
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Create menu bar and status bar
        self._setup_menu_bar(MainWindow)
        self._setup_status_bar(MainWindow)
        
        # Connect slots
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def _apply_stylesheet(self, MainWindow):
        """Apply comprehensive stylesheet for modern UI"""
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #f5f5f5;
            }

            QTabWidget::pane {
                border: 1px solid #c0c0c0;
                background-color: white;
                border-radius: 5px;
            }

            QTabWidget::tab-bar {
                left: 5px;
            }

            QTabBar::tab {
                background-color: #f0f0f0;
                border: 1px solid #c0c0c0;
                border-bottom-color: #c0c0c0;
                border-top-left-radius: 4px;
                border-top-right-radius: 4px;
                min-width: 120px;
                min-height: 30px;
                padding: 8px 16px;
                font-weight: bold;
                margin-right: 2px;
            }

            QTabBar::tab:selected {
                background-color: white;
                border-bottom-color: white;
                border-top: 2px solid #0078d4;
            }

            QTabBar::tab:hover:!selected {
                background-color: #e8e8e8;
            }

            QTabBar::tab:disabled {
                background-color: #f8f8f8;
                color: #888888;
                border-color: #e0e0e0;
            }

            QGroupBox {
                font-weight: bold;
                border: 1px solid #cccccc;
                border-radius: 5px;
                margin-top: 10px;
                padding-top: 5px;
                background-color: white;
            }

            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 8px 0 8px;
                background-color: white;
            }

            QPushButton {
                background-color: #0078d4;
                color: white;
                border: none;
                border-radius: 4px;
                font-weight: bold;
                padding: 8px 16px;
                min-height: 24px;
            }

            QPushButton:hover {
                background-color: #106ebe;
            }

            QPushButton:pressed {
                background-color: #005a9e;
            }

            QPushButton:disabled {
                background-color: #cccccc;
                color: #666666;
            }

            QProgressBar {
                border: 1px solid #cccccc;
                border-radius: 3px;
                text-align: center;
                font-size: 11px;
                background-color: #f0f0f0;
            }

            QProgressBar::chunk {
                background-color: #4CAF50;
                border-radius: 2px;
            }

            /* Add scrollbar styling for better appearance */
            QScrollBar:vertical {
                background: #f0f0f0;
                width: 12px;
                border-radius: 6px;
            }

            QScrollBar::handle:vertical {
                background: #c0c0c0;
                border-radius: 6px;
                min-height: 20px;
            }

            QScrollBar::handle:vertical:hover {
                background: #a0a0a0;
            }

            QScrollArea {
                border: none;
                background-color: transparent;
            }
        """)

    def _setup_central_widget(self, MainWindow):
        """Setup central widget with proper sizing policies"""
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        
        # Create main layout for central widget
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")

    def _setup_tab_widget(self):
        """Setup tab widget with responsive design"""
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setCurrentIndex(4)  # Analysis tab as per UI file
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        
        # Set size policy for responsive behavior
        self.tabWidget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        
        # Add to main layout
        self.main_layout.addWidget(self.tabWidget)

    def _create_all_tabs(self):
        """Create all tabs with responsive layouts"""
        tab_configs = [
            ("homeTab", "主页", "homeLayout"),
            ("configTab", "配置", "configLayout"), 
            ("testTab", "测试", "testLayout"),
            ("acquisitionTab", "采样", "acquisitionLayout"),
            ("analysisTab", "分析", "analysisLayout")
        ]
        
        for tab_name, tab_title, layout_name in tab_configs:
            self._create_responsive_tab(tab_name, tab_title, layout_name)

    def _create_responsive_tab(self, tab_name, tab_title, layout_name):
        """Create a single responsive tab with scroll support"""
        # Create tab widget
        tab_widget = QtWidgets.QWidget()
        tab_widget.setObjectName(tab_name)
        tab_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        
        # Create scroll area for the tab content
        scroll_area = QtWidgets.QScrollArea(tab_widget)
        scroll_area.setWidgetResizable(True)
        scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        scroll_area.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        
        # Create content widget for scroll area
        content_widget = QtWidgets.QWidget()
        content_widget.setObjectName(f"{tab_name}_content")
        content_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        
        # Create layout for content widget
        content_layout = QtWidgets.QVBoxLayout(content_widget)
        content_layout.setContentsMargins(20, 20, 20, 20)
        content_layout.setSpacing(15)
        content_layout.setObjectName(layout_name)
        
        # Set up the scroll area
        scroll_area.setWidget(content_widget)
        
        # Create main layout for tab widget
        tab_layout = QtWidgets.QVBoxLayout(tab_widget)
        tab_layout.setContentsMargins(0, 0, 0, 0)
        tab_layout.setSpacing(0)
        tab_layout.addWidget(scroll_area)
        
        # Add tab to tab widget
        self.tabWidget.addTab(tab_widget, tab_title)
        
        # Store references for easy access
        setattr(self, tab_name, tab_widget)
        setattr(self, layout_name, content_layout)
        setattr(self, f"{tab_name}_scroll", scroll_area)
        setattr(self, f"{tab_name}_content", content_widget)

    def _setup_status_area(self):
        """Setup status area with responsive design"""
        self.statusGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.statusGroupBox.setTitle("")  # Empty title as per UI file
        self.statusGroupBox.setObjectName("statusGroupBox")
        self.statusGroupBox.setFixedHeight(75)  # Fixed height for status area
        self.statusGroupBox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        
        # Add to main layout
        self.main_layout.addWidget(self.statusGroupBox)
        
        # Create status layout components
        self._create_status_layout()

    def _create_status_layout(self):
        """Create the status layout with all components"""
        self.statusLayout = QtWidgets.QHBoxLayout(self.statusGroupBox)
        self.statusLayout.setContentsMargins(10, 10, 10, 10)
        self.statusLayout.setSpacing(15)
        self.statusLayout.setObjectName("statusLayout")
        
        # Connect button
        self._create_connect_button()
        
        # Device info section
        self._create_device_info_section()
        
        # Connection info section
        self._create_connection_info_section()
        
        # Battery section
        self._create_battery_section()
        
        # Spacer
        self.statusSpacer = QtWidgets.QSpacerItem(
            40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum
        )
        self.statusLayout.addItem(self.statusSpacer)
        
        # Status info label
        self._create_status_info_label()

    def _create_connect_button(self):
        """Create connect button with proper sizing"""
        self.connectButton = QtWidgets.QPushButton(self.statusGroupBox)
        self.connectButton.setMinimumSize(QtCore.QSize(120, 40))
        self.connectButton.setMaximumSize(QtCore.QSize(150, 40))
        self.connectButton.setText("连接设备")
        self.connectButton.setObjectName("connectButton")
        self.statusLayout.addWidget(self.connectButton)

    def _create_device_info_section(self):
        """Create device information section"""
        self.deviceInfoLayout = QtWidgets.QVBoxLayout()
        self.deviceInfoLayout.setContentsMargins(0, 0, 0, 0)
        self.deviceInfoLayout.setSpacing(2)
        self.deviceInfoLayout.setObjectName("deviceInfoLayout")
        
        self.deviceIdLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.deviceIdLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.deviceIdLabel.setText("设备 ID: --")
        self.deviceIdLabel.setObjectName("deviceIdLabel")
        self.deviceInfoLayout.addWidget(self.deviceIdLabel)
        
        self.deviceTypeLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.deviceTypeLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.deviceTypeLabel.setText("设备类型: --")
        self.deviceTypeLabel.setObjectName("deviceTypeLabel")
        self.deviceInfoLayout.addWidget(self.deviceTypeLabel)
        
        self.statusLayout.addLayout(self.deviceInfoLayout)

    def _create_connection_info_section(self):
        """Create connection information section"""
        self.connectionInfoLayout = QtWidgets.QVBoxLayout()
        self.connectionInfoLayout.setContentsMargins(0, 0, 0, 0)
        self.connectionInfoLayout.setSpacing(2)
        self.connectionInfoLayout.setObjectName("connectionInfoLayout")
        
        self.connectionStatusLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.connectionStatusLabel.setStyleSheet("QLabel { color: #f44336; font-weight: bold; }")
        self.connectionStatusLabel.setText("⚫ 未连接")
        self.connectionStatusLabel.setObjectName("connectionStatusLabel")
        self.connectionInfoLayout.addWidget(self.connectionStatusLabel)
        
        self.deviceCountLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.deviceCountLabel.setText("数量: 0")
        self.deviceCountLabel.setObjectName("deviceCountLabel")
        self.connectionInfoLayout.addWidget(self.deviceCountLabel)
        
        self.statusLayout.addLayout(self.connectionInfoLayout)

    def _create_battery_section(self):
        """Create battery information section"""
        self.batteryLayout = QtWidgets.QVBoxLayout()
        self.batteryLayout.setContentsMargins(0, 0, 0, 0)
        self.batteryLayout.setSpacing(2)
        self.batteryLayout.setObjectName("batteryLayout")
        
        self.batteryLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.batteryLabel.setText("电量:")
        self.batteryLabel.setObjectName("batteryLabel")
        self.batteryLayout.addWidget(self.batteryLabel)
        
        self.batteryProgressBar = QtWidgets.QProgressBar(self.statusGroupBox)
        self.batteryProgressBar.setMinimumSize(QtCore.QSize(120, 20))
        self.batteryProgressBar.setMaximumSize(QtCore.QSize(200, 25))
        self.batteryProgressBar.setValue(0)
        self.batteryProgressBar.setObjectName("batteryProgressBar")
        self.batteryLayout.addWidget(self.batteryProgressBar)
        
        self.statusLayout.addLayout(self.batteryLayout)

    def _create_status_info_label(self):
        """Create status information label"""
        self.statusInfoLabel = QtWidgets.QLabel(self.statusGroupBox)
        self.statusInfoLabel.setStyleSheet("QLabel { color: #3498db; font-weight: bold; }")
        self.statusInfoLabel.setText("Status: Ready to connect")
        self.statusInfoLabel.setWordWrap(True)
        self.statusInfoLabel.setObjectName("statusInfoLabel")
        self.statusLayout.addWidget(self.statusInfoLabel)

    def _setup_menu_bar(self, MainWindow):
        """Create menu bar and actions"""
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        
        # Create menus
        self._create_file_menu()
        self._create_settings_menu()
        self._create_help_menu()
        
        MainWindow.setMenuBar(self.menubar)
        
        # Create actions
        self._create_menu_actions(MainWindow)
        
        # Add actions to menus
        self._populate_menus()

    def _create_file_menu(self):
        """Create file menu"""
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setTitle("File(&F)")
        self.fileMenu.setObjectName("fileMenu")

    def _create_settings_menu(self):
        """Create settings menu"""
        self.settingsMenu = QtWidgets.QMenu(self.menubar)
        self.settingsMenu.setTitle("Settings(&S)")
        self.settingsMenu.setObjectName("settingsMenu")

    def _create_help_menu(self):
        """Create help menu"""
        self.helpMenu = QtWidgets.QMenu(self.menubar)
        self.helpMenu.setTitle("Help(&H)")
        self.helpMenu.setObjectName("helpMenu")

    def _create_menu_actions(self, MainWindow):
        """Create menu actions"""
        # File menu actions
        self.saveAction = QtWidgets.QAction(MainWindow)
        self.saveAction.setText("&Save")
        self.saveAction.setShortcut("Ctrl+S")
        self.saveAction.setObjectName("saveAction")
        
        self.exportAction = QtWidgets.QAction(MainWindow)
        self.exportAction.setText("&Export Data")
        self.exportAction.setShortcut("Ctrl+E")
        self.exportAction.setObjectName("exportAction")
        
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setText("E&xit")
        self.exitAction.setShortcut("Alt+F4")
        self.exitAction.setObjectName("exitAction")
        
        # Settings menu actions
        self.preferencesAction = QtWidgets.QAction(MainWindow)
        self.preferencesAction.setText("&Preferences")
        self.preferencesAction.setObjectName("preferencesAction")
        
        # Help menu actions
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setText("&About")
        self.aboutAction.setObjectName("aboutAction")

    def _populate_menus(self):
        """Add actions to menus"""
        # File menu
        self.fileMenu.addAction(self.saveAction)
        self.fileMenu.addAction(self.exportAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.exitAction)
        
        # Settings menu
        self.settingsMenu.addAction(self.preferencesAction)
        
        # Help menu
        self.helpMenu.addAction(self.aboutAction)
        
        # Add menus to menu bar
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.settingsMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

    def _setup_status_bar(self, MainWindow):
        """Create status bar"""
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

    def retranslateUi(self, MainWindow):
        """Retranslate UI elements"""
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "fNIRS Data Acquisition System"))
        
        # Tab titles
        tab_titles = ["主页", "配置", "测试", "采样", "分析"]
        for i, title in enumerate(tab_titles):
            if i < self.tabWidget.count():
                self.tabWidget.setTabText(i, _translate("MainWindow", title))
        
        # Status elements
        self.connectButton.setText(_translate("MainWindow", "连接设备"))
        self.deviceIdLabel.setText(_translate("MainWindow", "设备 ID: --"))
        self.deviceTypeLabel.setText(_translate("MainWindow", "设备类型: --"))
        self.connectionStatusLabel.setText(_translate("MainWindow", "⚫ 未连接"))
        self.deviceCountLabel.setText(_translate("MainWindow", "数量: 0"))
        self.batteryLabel.setText(_translate("MainWindow", "电量:"))
        self.statusInfoLabel.setText(_translate("MainWindow", "Status: Ready to connect"))
        
        # Menu items
        self.fileMenu.setTitle(_translate("MainWindow", "File(&F)"))
        self.settingsMenu.setTitle(_translate("MainWindow", "Settings(&S)"))
        self.helpMenu.setTitle(_translate("MainWindow", "Help(&H)"))
        self.saveAction.setText(_translate("MainWindow", "&Save"))
        self.exportAction.setText(_translate("MainWindow", "&Export Data"))
        self.exitAction.setText(_translate("MainWindow", "E&xit"))
        self.preferencesAction.setText(_translate("MainWindow", "&Preferences"))
        self.aboutAction.setText(_translate("MainWindow", "&About"))

    def get_tab_content_layout(self, tab_name):
        """Get the content layout for a specific tab"""
        layout_name = f"{tab_name}Layout"
        return getattr(self, layout_name, None)
    
    def get_tab_scroll_area(self, tab_name):
        """Get the scroll area for a specific tab"""
        scroll_name = f"{tab_name}_scroll"
        return getattr(self, scroll_name, None)
    
    def clear_tab_content(self, tab_name):
        """清理指定tab的内容"""
        layout_name = f"{tab_name}Layout"
        layout = getattr(self, layout_name, None)
        
        if layout:
            # 清理布局中的所有widget
            while layout.count():
                child = layout.takeAt(0)
                if child.widget():
                    child.widget().deleteLater()
    
    def has_tab_content(self, tab_name):
        """检查tab是否有内容"""
        layout_name = f"{tab_name}Layout"
        layout = getattr(self, layout_name, None)
        return layout and layout.count() > 0


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())