# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qualify.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        Form.setStyleSheet("QWidget {\n"
                          "    background-color: #f5f5f5;\n"
                          "    font-family: Arial, sans-serif;\n"
                          "}\n"
                          "\n"
                          "QLabel {\n"
                          "    color: #333;\n"
                          "    font-weight: bold;\n"
                          "}\n"
                          "\n"
                          "QComboBox {\n"
                          "    background-color: white;\n"
                          "    border: 2px solid #ddd;\n"
                          "    border-radius: 4px;\n"
                          "    padding: 2px 8px;\n"
                          "}\n"
                          "\n"
                          "QPushButton {\n"
                          "    background-color: #4CAF50;\n"
                          "    color: white;\n"
                          "    border: none;\n"
                          "    border-radius: 4px;\n"
                          "    padding: 8px 16px;\n"
                          "    font-weight: bold;\n"
                          "}\n"
                          "\n"
                          "QPushButton:hover {\n"
                          "    background-color: #45a049;\n"
                          "}\n"
                          "\n"
                          "QPushButton:pressed {\n"
                          "    background-color: #3d8b40;\n"
                          "}\n"
                          "\n"
                          "QLineEdit {\n"
                          "    background-color: white;\n"
                          "    border: 1px solid #ddd;\n"
                          "    border-radius: 3px;\n"
                          "    padding: 2px 5px;\n"
                          "    font-family: monospace;\n"
                          "}\n"
                          "\n"
                          "QGroupBox {\n"
                          "    font-weight: bold;\n"
                          "    border: 2px solid #cccccc;\n"
                          "    border-radius: 5px;\n"
                          "    margin-top: 1ex;\n"
                          "    padding-top: 10px;\n"
                          "}\n"
                          "\n"
                          "QGroupBox::title {\n"
                          "    subcontrol-origin: margin;\n"
                          "    left: 10px;\n"
                          "    padding: 0 5px 0 5px;\n"
                          "}")
        
        # Header Group
        self.headerGroup = QtWidgets.QGroupBox(Form)
        self.headerGroup.setGeometry(QtCore.QRect(20, 20, 1160, 80))
        self.headerGroup.setObjectName("headerGroup")
        
        # Method selection
        self.methodLabel = QtWidgets.QLabel(self.headerGroup)
        self.methodLabel.setGeometry(QtCore.QRect(20, 30, 100, 20))
        self.methodLabel.setObjectName("methodLabel")
        
        self.methodComboBox = QtWidgets.QComboBox(self.headerGroup)
        self.methodComboBox.setGeometry(QtCore.QRect(130, 28, 200, 25))
        self.methodComboBox.setObjectName("methodComboBox")
        self.methodComboBox.addItem("")
        self.methodComboBox.addItem("")
        
        # Status label
        self.statusLabel = QtWidgets.QLabel(self.headerGroup)
        self.statusLabel.setGeometry(QtCore.QRect(400, 30, 120, 20))
        self.statusLabel.setObjectName("statusLabel")
        self.statusLabel.setStyleSheet("color: #666;")
        
        # Control buttons
        self.startButton = QtWidgets.QPushButton(self.headerGroup)
        self.startButton.setGeometry(QtCore.QRect(900, 25, 80, 30))
        self.startButton.setObjectName("startButton")
        
        self.stopButton = QtWidgets.QPushButton(self.headerGroup)
        self.stopButton.setGeometry(QtCore.QRect(990, 25, 80, 30))
        self.stopButton.setObjectName("stopButton")
        self.stopButton.setStyleSheet("background-color: #f44336;")
        
        # Channel Group
        self.channelGroup = QtWidgets.QGroupBox(Form)
        self.channelGroup.setGeometry(QtCore.QRect(20, 120, 1160, 600))
        self.channelGroup.setObjectName("channelGroup")
        
        # Header labels
        self.channelHeaderLabel = QtWidgets.QLabel(self.channelGroup)
        self.channelHeaderLabel.setGeometry(QtCore.QRect(25, 30, 80, 25))
        self.channelHeaderLabel.setObjectName("channelHeaderLabel")
        self.channelHeaderLabel.setStyleSheet("background-color: #e0e0e0; border: 1px solid #ccc; padding: 5px;")
        self.channelHeaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.nm750HeaderLabel = QtWidgets.QLabel(self.channelGroup)
        self.nm750HeaderLabel.setGeometry(QtCore.QRect(105, 30, 120, 25))
        self.nm750HeaderLabel.setObjectName("nm750HeaderLabel")
        self.nm750HeaderLabel.setStyleSheet("background-color: #e0e0e0; border: 1px solid #ccc; padding: 5px;")
        self.nm750HeaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.nm850HeaderLabel = QtWidgets.QLabel(self.channelGroup)
        self.nm850HeaderLabel.setGeometry(QtCore.QRect(225, 30, 120, 25))
        self.nm850HeaderLabel.setObjectName("nm850HeaderLabel")
        self.nm850HeaderLabel.setStyleSheet("background-color: #e0e0e0; border: 1px solid #ccc; padding: 5px;")
        self.nm850HeaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.qualityHeaderLabel = QtWidgets.QLabel(self.channelGroup)
        self.qualityHeaderLabel.setGeometry(QtCore.QRect(345, 30, 100, 25))
        self.qualityHeaderLabel.setObjectName("qualityHeaderLabel")
        self.qualityHeaderLabel.setStyleSheet("background-color: #e0e0e0; border: 1px solid #ccc; padding: 5px;")
        self.qualityHeaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.unitLabel = QtWidgets.QLabel(self.channelGroup)
        self.unitLabel.setGeometry(QtCore.QRect(445, 30, 50, 25))
        self.unitLabel.setObjectName("unitLabel")
        self.unitLabel.setStyleSheet("background-color: #e0e0e0; border: 1px solid #ccc; padding: 5px;")
        self.unitLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        # Scroll area for channel data
        self.channelScrollArea = QtWidgets.QScrollArea(self.channelGroup)
        self.channelScrollArea.setGeometry(QtCore.QRect(20, 60, 1120, 520))
        self.channelScrollArea.setWidgetResizable(True)
        self.channelScrollArea.setObjectName("channelScrollArea")
        self.channelScrollArea.setStyleSheet("QScrollArea {\n"
                                           "    border: 1px solid #ccc;\n"
                                           "    background-color: white;\n"
                                           "}")
        
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1118, 518))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.channelScrollArea.setWidget(self.scrollAreaWidgetContents)
        
        # Bottom control buttons
        self.completeButton = QtWidgets.QPushButton(Form)
        self.completeButton.setGeometry(QtCore.QRect(1050, 740, 100, 35))
        self.completeButton.setObjectName("completeButton")
        
        self.resetButton = QtWidgets.QPushButton(Form)
        self.resetButton.setGeometry(QtCore.QRect(930, 740, 100, 35))
        self.resetButton.setObjectName("resetButton")
        self.resetButton.setStyleSheet("background-color: #ff9800;")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "fNIRS Channel Quality Assessment"))
        self.headerGroup.setTitle(_translate("Form", "Assessment Configuration"))
        self.methodLabel.setText(_translate("Form", "评估方法："))
        self.methodComboBox.setItemText(0, _translate("Form", "光电信号强度"))
        self.methodComboBox.setItemText(1, _translate("Form", "头皮耦合指数(SCI)"))
        self.statusLabel.setText(_translate("Form", "更新状态：准备中"))
        self.startButton.setText(_translate("Form", "开始"))
        self.stopButton.setText(_translate("Form", "停止"))
        self.channelGroup.setTitle(_translate("Form", "Channel Quality Assessment"))
        self.channelHeaderLabel.setText(_translate("Form", "Channel"))
        self.nm750HeaderLabel.setText(_translate("Form", "750nm Signal"))
        self.nm850HeaderLabel.setText(_translate("Form", "850nm Signal"))
        self.qualityHeaderLabel.setText(_translate("Form", "Quality Status"))
        self.unitLabel.setText(_translate("Form", "Unit"))
        self.completeButton.setText(_translate("Form", "完成"))
        self.resetButton.setText(_translate("Form", "重置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())