# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Connect.setGeometry(QtCore.QRect(1000, 30, 60, 30))
        self.Button_Connect.setObjectName("Button_Connect")
        self.Button_Disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Disconnect.setGeometry(QtCore.QRect(1070, 30, 60, 30))
        self.Button_Disconnect.setObjectName("Button_Disconnect")
        self.Button_Disconnect.setEnabled(False)
        self.Button_StartSample = QtWidgets.QPushButton(self.centralwidget)
        self.Button_StartSample.setGeometry(QtCore.QRect(1140, 30, 60, 30))
        self.Button_StartSample.setObjectName("Button_StartSample")
        self.Button_StartSample.setEnabled(False)
        self.Button_Record = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Record.setGeometry(QtCore.QRect(1210, 30, 60, 30))
        self.Button_Record.setObjectName("Button_Record")
        self.Button_Record.setEnabled(False)
        self.Record_click_count = 0
        self.Button_StopSample = QtWidgets.QPushButton(self.centralwidget)
        self.Button_StopSample.setGeometry(QtCore.QRect(1280, 30, 60, 30))
        self.Button_StopSample.setObjectName("Button_StopSample")
        self.Button_StopSample.setEnabled(False)
        
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(39, 199, 1521, 621))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.Widget_Sensors = QtWidgets.QWidget()
        self.Widget_Sensors.setGeometry(QtCore.QRect(0, 0, 1519, 619))
        self.Widget_Sensors.setObjectName("Widget_Sensors")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Widget_Sensors)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 1521, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VLayout_Sensors = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VLayout_Sensors.setContentsMargins(0, 0, 0, 0)
        self.VLayout_Sensors.setObjectName("VLayout_Sensors")
        self.scrollArea.setWidget(self.Widget_Sensors)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Button_Connect.clicked.connect(self.BottonConnectClicked) # type: ignore
        self.Button_Disconnect.clicked.connect(self.BottonDisconnectClicked) # type: ignore
        self.Button_StartSample.clicked.connect(self.BottonStartSampleClicked) # type: ignore   
        self.Button_StopSample.clicked.connect(self.BottonStopSampleClicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Connect.setText(_translate("MainWindow", "连接"))
        self.Button_Disconnect.setText(_translate("MainWindow", "断开"))
        self.Button_StartSample.setText(_translate("MainWindow", "开始"))
        self.Button_Record.setText(_translate("MainWindow", "记录"))    
        self.Button_StopSample.setText(_translate("MainWindow", "结束"))
        
    def BottonConnectClicked(self):
        self.Button_Disconnect.setEnabled(True)
        self.Button_StartSample.setEnabled(True)
        
    def BottonDisconnectClicked(self):
        self.Button_StartSample.setEnabled(False)
        self.Button_Record.setEnabled(False)
        self.Button_StopSample.setEnabled(False)
        
    def BottonStartSampleClicked(self):
        self.Record_click_count = 0
        self.Button_Record.setEnabled(True)
        self.Button_StopSample.setEnabled(True)
        
    def BottonRecordClicked(self):
        self.Record_click_count += 1

        
    def BottonStopSampleClicked(self):
        self.Button_Record.setEnabled(False)
        self.Button_StopSample.setEnabled(False)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
