# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SensorWidget(object):
    def setupUi(self, SensorWidget):
        SensorWidget.setObjectName("SensorWidget")
        SensorWidget.resize(1500, 300)
        self.Label_SensorID = QtWidgets.QLabel(SensorWidget)
        self.Label_SensorID.setGeometry(QtCore.QRect(10, 10, 191, 16))
        self.Label_SensorID.setObjectName("Label_SensorID")
        self.Label_SensorType = QtWidgets.QLabel(SensorWidget)
        self.Label_SensorType.setGeometry(QtCore.QRect(210, 10, 191, 16))
        self.Label_SensorType.setObjectName("Label_SensorType")
        self.Label_Battery = QtWidgets.QLabel(SensorWidget)
        self.Label_Battery.setGeometry(QtCore.QRect(370, 10, 191, 16))
        self.Label_Battery.setObjectName("Label_Battery")
        self.ComboBox_SampleRate = QtWidgets.QComboBox(SensorWidget)
        self.ComboBox_SampleRate.setGeometry(QtCore.QRect(1090, 0, 71, 31))
        self.ComboBox_SampleRate.setEditable(True)
        self.ComboBox_SampleRate.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.ComboBox_SampleRate.setObjectName("ComboBox_SampleRate")
        self.ComboBox_SampleRate.addItem("")
        self.ComboBox_SampleRate.addItem("")
        self.Label_SampleRateText = QtWidgets.QLabel(SensorWidget)
        self.Label_SampleRateText.setGeometry(QtCore.QRect(1020, 10, 61, 16))
        self.Label_SampleRateText.setObjectName("Label_SampleRateText")
        self.Button_SampleRate = QtWidgets.QPushButton(SensorWidget)
        self.Button_SampleRate.setGeometry(QtCore.QRect(1180, 0, 61, 31))
        self.Button_SampleRate.setObjectName("Button_SampleRate")
        self.Label_Channel = QtWidgets.QLabel(SensorWidget)
        self.Label_Channel.setGeometry(QtCore.QRect(1260, 10, 111, 16))
        self.Label_Channel.setObjectName("Label_Channel")
        self.SpinBox_Lights = QtWidgets.QSpinBox(SensorWidget)
        self.SpinBox_Lights.setGeometry(QtCore.QRect(1320, 40, 42, 22))
        self.SpinBox_Lights.setMinimum(1)
        self.SpinBox_Lights.setMaximum(99)
        self.SpinBox_Lights.setProperty("value", 8)
        self.SpinBox_Lights.setObjectName("SpinBox_Lights")
        self.SpinBox_Detectors = QtWidgets.QSpinBox(SensorWidget)
        self.SpinBox_Detectors.setGeometry(QtCore.QRect(1440, 40, 42, 22))
        self.SpinBox_Detectors.setMinimum(1)
        self.SpinBox_Detectors.setMaximum(99)
        self.SpinBox_Detectors.setProperty("value", 8)
        self.SpinBox_Detectors.setObjectName("SpinBox_Detectors")
        self.Label_LightsText = QtWidgets.QLabel(SensorWidget)
        self.Label_LightsText.setGeometry(QtCore.QRect(1260, 40, 61, 16))
        self.Label_LightsText.setObjectName("Label_LightsText")
        self.Label_DetectorsText = QtWidgets.QLabel(SensorWidget)
        self.Label_DetectorsText.setGeometry(QtCore.QRect(1380, 40, 61, 16))
        self.Label_DetectorsText.setObjectName("Label_DetectorsText")
        self.ScrollArea_Channels = QtWidgets.QScrollArea(SensorWidget)
        self.ScrollArea_Channels.setGeometry(QtCore.QRect(1260, 70, 231, 211))
        self.ScrollArea_Channels.setWidgetResizable(True)
        self.ScrollArea_Channels.setObjectName("ScrollArea_Channels")
        self.Widget_Channels = QtWidgets.QWidget()
        self.Widget_Channels.setGeometry(QtCore.QRect(0, 0, 229, 209))
        self.Widget_Channels.setObjectName("Widget_Channels")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Widget_Channels)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 231, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.GridLayout_Channels = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.GridLayout_Channels.setContentsMargins(0, 0, 0, 0)
        self.GridLayout_Channels.setObjectName("GridLayout_Channels")
        self.ScrollArea_Channels.setWidget(self.Widget_Channels)
        self.Button_Channels = QtWidgets.QPushButton(SensorWidget)
        self.Button_Channels.setGeometry(QtCore.QRect(1360, 0, 61, 31))
        self.Button_Channels.setObjectName("Button_Channels")
        self.ScrollArea_Plot = QtWidgets.QScrollArea(SensorWidget)
        self.ScrollArea_Plot.setGeometry(QtCore.QRect(10, 40, 1221, 261))
        self.ScrollArea_Plot.setWidgetResizable(True)
        self.ScrollArea_Plot.setObjectName("ScrollArea_Plot")
        self.Widget_Plot = QtWidgets.QWidget()
        self.Widget_Plot.setGeometry(QtCore.QRect(0, 0, 1219, 259))
        self.Widget_Plot.setObjectName("Widget_Plot")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Widget_Plot)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1221, 261))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HLayout_Plot = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HLayout_Plot.setContentsMargins(0, 0, 0, 0)
        self.HLayout_Plot.setObjectName("HLayout_Plot")
        self.ScrollArea_Plot.setWidget(self.Widget_Plot)

        self.retranslateUi(SensorWidget)
        QtCore.QMetaObject.connectSlotsByName(SensorWidget)

    def retranslateUi(self, SensorWidget):
        _translate = QtCore.QCoreApplication.translate
        SensorWidget.setWindowTitle(_translate("SensorWidget", "Form"))
        self.Label_SensorID.setText(_translate("SensorWidget", "传感器ID: 000000"))
        self.Label_SensorType.setText(_translate("SensorWidget", "类型: fNIRS"))
        self.Label_Battery.setText(_translate("SensorWidget", "电量: 0%"))
        self.ComboBox_SampleRate.setItemText(0, _translate("SensorWidget", "10"))
        self.ComboBox_SampleRate.setItemText(1, _translate("SensorWidget", "20"))
        self.Label_SampleRateText.setText(_translate("SensorWidget", "采样率"))
        self.Button_SampleRate.setText(_translate("SensorWidget", "设置"))
        self.Label_Channel.setText(_translate("SensorWidget", "通道配置"))
        self.Label_LightsText.setText(_translate("SensorWidget", "光源"))
        self.Label_DetectorsText.setText(_translate("SensorWidget", "探测器"))
        self.Button_Channels.setText(_translate("SensorWidget", "设置"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SensorWidget = QtWidgets.QWidget()
    ui = Ui_SensorWidget()
    ui.setupUi(SensorWidget)
    SensorWidget.show()
    sys.exit(app.exec_())
